const constantDataType = {
    USER : 'USER',
    ADMIN : 'ADMIN',
    CONVERTION_INIT : 'CONVERTION_INIT',
    CONVERT : 'CONVERT',
    TRANSECTION : 'TRANSECTION',
    TRANSECTION_RESULT : 'TRANSECTION_RESULT', 
    ADD_TRANSECTION : 'ADD_TRANSECTION',
    ADD_TRANSECTION_SAVE : 'ADD_TRANSECTION_SAVE',
    ADD_WALLET_CARD: 'ADD_WALLET_CARD',
    ADD_WALLET_CARD_SAVE : 'ADD_WALLET_CARD_SAVE',
    WALLET_CARD: 'WALLET_CARD',
    WALLET_CARD_RESULT : 'WALLET_CARD_RESULT',
    DELETE_TRANSECTION: 'DELETE_TRANSECTION',
    DELETE_TRANSECTION_RESULT: 'DELETE_TRANSECTION_RESULT',
    WALLET_REFRESH: 'WALLET_REFRESH'
}

export default constantDataType